#!/bin/bash
# PORTMASTER: swordigo, Swordigo.sh
# Swordigo — generated by nxbootstrap 0.6.0.

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

# A signal before the game starts (mapper/extraction can take seconds) must
# still hand the screen back to the frontend instead of dying by default.
trap 'echo "== aborted before game start =="; command -v pm_finish >/dev/null 2>&1 && pm_finish; exit 143' INT TERM HUP

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
elif [ -d "/storage/roms/ports/PortMaster/" ]; then
  controlfolder="/storage/roms/ports/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

if [ -f "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  [ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
  command -v get_controls >/dev/null 2>&1 && get_controls
fi

GAMEDIR="/$directory/ports/swordigo"
[ -d "$GAMEDIR" ] || GAMEDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)/swordigo"
# Physical path: ROM roots are often symlinks (/roms -> /storage/roms) and
# tools that compare canonical containment would reject the logical path.
cd "$GAMEDIR" || exit 1
GAMEDIR=$(pwd -P)

[ -s "$GAMEDIR/log.txt" ] && mv -f "$GAMEDIR/log.txt" "$GAMEDIR/log.prev.txt" 2>/dev/null
exec > "$GAMEDIR/log.txt" 2>&1
echo "== Swordigo | nxbootstrap 0.6.0 | cfw=${CFW_NAME:-none} =="

# Exec bits do not survive zip/FAT/Windows extraction.
$ESUDO chmod +x "$GAMEDIR/swordigo-nextos-v109" "$GAMEDIR/nxextract-ui" \
  "$GAMEDIR"/*.sh 2>/dev/null || true
$ESUDO chmod 666 "$CUR_TTY" /dev/uinput 2>/dev/null || true

# One instance only: kernel inode lock on the binary itself (works on FAT).
# Two instances fight over fb0/DRM master; the second opens black or wedges.
exec 9<"$GAMEDIR/swordigo-nextos-v109"
if ! flock -n 9; then
  echo "another instance holds the lock; not double-launching"
  command -v pm_finish >/dev/null 2>&1 && pm_finish
  exit 1
fi

# NXExtract owner-data phase (BYO data): runs before the game, other process.
NXDIR=""
[ -f "$GAMEDIR/nxextract/run-extractor.sh" ] && NXDIR="$GAMEDIR/nxextract"
[ -z "$NXDIR" ] && [ -f "$GAMEDIR/run-extractor.sh" ] && NXDIR="$GAMEDIR"
if [ -n "$NXDIR" ] && [ -f "$GAMEDIR/extractor.json" ]; then
  $ESUDO chmod +x "$NXDIR/nxextract-ui" 2>/dev/null || true
  NXEXTRACT_GAME_DIR="$GAMEDIR" \
    bash "$NXDIR/nxextract-runtime-env.sh" \
    bash "$NXDIR/run-extractor.sh" || {
      echo "ERROR: game data installation did not complete"
      command -v pm_finish >/dev/null 2>&1 && pm_finish
      exit 1
    }
fi
# Saves and configuration stay inside the port directory.
export HOME="$GAMEDIR"
# Firmware libraries first, then the game's own directory.
LIBS=""
for d in "$controlfolder/libs" /usr/lib/aarch64-linux-gnu /usr/lib64 /usr/lib; do
  [ -n "$d" ] && [ -d "$d" ] && LIBS="${LIBS:+$LIBS:}$d"
done
export LD_LIBRARY_PATH="${LIBS}:$GAMEDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Optional per-port adapter: may export env or replace $BIN / $BIN_PRELOAD.
BIN="$GAMEDIR/swordigo-nextos-v109"
[ -f "$GAMEDIR/port-env.sh" ] && [ ! -L "$GAMEDIR/port-env.sh" ] && . "$GAMEDIR/port-env.sh"

command -v pm_platform_helper >/dev/null 2>&1 && pm_platform_helper "$BIN"

if [ -n "$BIN_PRELOAD" ]; then
  LD_PRELOAD="$BIN_PRELOAD${LD_PRELOAD:+:$LD_PRELOAD}" "$BIN" "$GAMEDIR" "$@" &
else
  "$BIN" "$GAMEDIR" "$@" &
fi
game_pid=$!
trap 'kill -TERM "$game_pid" 2>/dev/null' INT TERM HUP
wait "$game_pid"; status=$?
# 128+n can be the trap interrupting wait, not the game dying: re-wait for
# the child's real status instead of reporting a lying 143 to the frontend.
while [ "$status" -gt 128 ] && kill -0 "$game_pid" 2>/dev/null; do
  wait "$game_pid"; status=$?
done
trap - INT TERM HUP
echo "== end (status $status) =="

# The game may leave the console keymap off (K_OFF); reset before handing back.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && printf '\033c' > "$CUR_TTY" 2>/dev/null
command -v pm_finish >/dev/null 2>&1 && pm_finish
exit $status
