#!/bin/bash
# PORTMASTER: swordigo, Swordigo.sh
# Generated by nxbootstrap. Public entry point and declarative port contract.

PORT_ID=swordigo
PORT_TITLE=Swordigo
NXPORT_ID=swordigo
NXPORT_TITLE=Swordigo
NXPORT_SCHEMA_VERSION=2
NXPORT_ARCH=aarch64
NXPORT_INTERPRETER=/lib/ld-linux-aarch64.so.1
NXPORT_EXECUTABLE=swordigo-nextos-v108
NXPORT_ARGUMENT_MODE=game-dir-and-passthrough
NXPORT_HOME_MODE=port
NXPORT_NXEXTRACT=yes
NXPORT_NXEXTRACT_VERSION=1.2.6
NXPORT_BOOTSTRAP_VERSION=0.5.1
NXPORT_BOOTSTRAP_LIBRARY=nxbootstrap-0.5.1.sh
NXPORT_BOOTSTRAP_SHA256=71bd91ef039feb4ed60aa0a1b26eaddafc1ceef80cdf34051fc6aacd2fdae902
NXPORT_MANIFEST_SHA256=863ed7e3898d10758e1f659d19bc94d8d7aefb046c547ddf81dd0c2a4fe92ab1
NXPORT_DEPLOYMENT_ID=d466c521061221d2675d73b2af4f95c4657c9850e333c57734c8ab2be51b687b
NXPORT_DEPLOYMENT_RECEIPT='{
  "bootstrap": {
    "filename": "nxbootstrap-0.5.1.sh",
    "sha256": "71bd91ef039feb4ed60aa0a1b26eaddafc1ceef80cdf34051fc6aacd2fdae902",
    "version": "0.5.1"
  },
  "deployment_id": "d466c521061221d2675d73b2af4f95c4657c9850e333c57734c8ab2be51b687b",
  "launcher_name": "Swordigo.sh",
  "nxport_sha256": "863ed7e3898d10758e1f659d19bc94d8d7aefb046c547ddf81dd0c2a4fe92ab1",
  "port_id": "swordigo",
  "schema_version": 1
}
'
NXPORT_REQUIRED_FILES='swordigo-nextos-v108
libswordigo.so
res/7c.mp3
alsoft.conf'
NXPORT_PRIVATE_LIBRARY_PATHS=''
NXPORT_PREPARE_SCRIPT=''
NXPORT_REQUIRED_CAPABILITIES='host.portmaster
graphics.window
graphics.egl
graphics.drawable
audio.output-open
input.controller-mapping
input.controller-api'
NXPORT_ENABLED_QUIRKS='game.swordigo.present-alpha-one
game.swordigo.fullscreen-desktop
game.swordigo.present-finish'
NXPORT_RUNTIME_REPORT=log-and-logo

NXPORT_LAUNCHER_STAGE=initialize
NXPORT_LAUNCHER_COMPLETED=0
NXPORT_LAUNCHER_ERROR=
NXPORT_LAUNCHER_CANDIDATE=
NXPORT_BOOTSTRAP_PATH=

nxport_launcher_notify() {
  local message=$1 log=$2 tty
  [[ ${NXBOOTSTRAP_TEST_NO_TTY:-0} != 1 ]] || return 0
  for tty in /dev/tty0 /dev/console; do
    if [[ -c $tty && ! -L $tty ]]; then
      printf '%s; details: %s\n' "$message" "$log" > "$tty" 2>/dev/null &&
        return 0
    fi
  done
  return 0
}

nxport_launcher_on_exit() {
  local status=$1 message details directory existing log duplicate notified=0
  local -a destinations=()
  (( status != 0 )) || return 0
  [[ ${NXPORT_LAUNCHER_COMPLETED:-0} != 1 ]] || return 0

  message=${NXPORT_LAUNCHER_ERROR:-"${PORT_TITLE:-Port}: launcher failed before nxbootstrap opened its runtime log"}
  details="stage=${NXPORT_LAUNCHER_STAGE:-unknown}
status=$status
launcher_original=${NXPORT_LAUNCHER_ORIGINAL:-${ORIGINAL_SELF:-unknown}}
launcher_resolved=${NXPORT_LAUNCHER_RESOLVED:-${SELF:-unknown}}
candidate=${NXPORT_LAUNCHER_CANDIDATE:-none}
bootstrap=${NXPORT_BOOTSTRAP_PATH:-none}
bootstrap_filename_expected=${NXPORT_BOOTSTRAP_LIBRARY:-unknown}
bootstrap_version_expected=${NXPORT_BOOTSTRAP_VERSION:-unknown}
bootstrap_sha256_expected=${NXPORT_BOOTSTRAP_SHA256:-unknown}
manifest_sha256_expected=${NXPORT_MANIFEST_SHA256:-unknown}
deployment_id_expected=${NXPORT_DEPLOYMENT_ID:-unknown}
paths tried:
${TRIED:-none}"
  printf '%s\n%s\n' "$message" "$details" >&2
  umask 077
  for directory in "${ORIGINAL_DIR:-}" "${SCRIPT_DIR:-}" "${TMPDIR:-/tmp}"; do
    [[ -n $directory && -d $directory ]] || continue
    duplicate=0
    for existing in "${destinations[@]}"; do
      if [[ $existing == "$directory" ]]; then
        duplicate=1
        break
      fi
    done
    (( duplicate == 0 )) || continue
    destinations+=("$directory")
    log=$directory/${PORT_ID:-port}-launcher-error.$$.log
    if (set -C; umask 077; printf '%s\n%s\n' "$message" "$details" > "$log") \
        2>/dev/null; then
      if (( notified == 0 )); then
        nxport_launcher_notify "$message" "$log"
        notified=1
      fi
    fi
  done
  return 0
}

trap 'nxport_launcher_on_exit $?' EXIT

nxport_deployment_receipt_matches() {
  local receipt=$1 line actual= expected first=1
  [[ -r $receipt ]] || return 1
  while IFS= read -r line || [[ -n $line ]]; do
    if (( first == 0 )); then
      actual+=$'\n'
    fi
    actual+=$line
    first=0
  done < "$receipt"
  (( first == 0 )) || return 1
  expected=${NXPORT_DEPLOYMENT_RECEIPT%$'\n'}
  [[ $actual == "$expected" ]]
}

nxport_file_sha256_matches() {
  local path=$1 expected=$2 actual
  command -v sha256sum >/dev/null 2>&1 || return 0
  actual=$(sha256sum "$path" 2>/dev/null) || return 1
  actual=${actual%%[[:space:]]*}
  [[ $actual == "$expected" ]]
}

NXPORT_LAUNCHER_STAGE=resolve-launcher
ORIGINAL_SELF=${BASH_SOURCE[0]}
ORIGINAL_DIR=$(CDPATH= cd -- "$(dirname -- "$ORIGINAL_SELF")" 2>/dev/null && pwd -P) ||
  ORIGINAL_DIR=.
SELF=$ORIGINAL_SELF
if [[ -L $SELF ]]; then
  if command -v readlink >/dev/null 2>&1; then
    RESOLVED=$(readlink -f -- "$SELF" 2>/dev/null || true)
    if [[ -n $RESOLVED ]]; then
      SELF=$RESOLVED
    else
      link_depth=0
      while [[ -L $SELF && $link_depth -lt 16 ]]; do
        LINK=$(readlink -- "$SELF" 2>/dev/null || true)
        case $LINK in
          /*) SELF=$LINK ;;
          ?*) SELF=$(dirname -- "$SELF")/$LINK ;;
          *) break ;;
        esac
        link_depth=$((link_depth + 1))
      done
      [[ $link_depth -lt 16 ]] || exit 1
    fi
  fi
fi
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$SELF")" 2>/dev/null && pwd -P) ||
  exit 1
NXPORT_LAUNCHER_ORIGINAL=$ORIGINAL_SELF
NXPORT_LAUNCHER_RESOLVED=$SELF
export NXPORT_LAUNCHER_ORIGINAL NXPORT_LAUNCHER_RESOLVED

NXPORT_LAUNCHER_STAGE=discover-runtime
TRIED=
try_port() {
  local candidate=$1 bootstrap manifest receipt status
  shift
  TRIED="${TRIED}${TRIED:+
}$candidate"
  bootstrap=$candidate/$NXPORT_BOOTSTRAP_LIBRARY
  manifest=$candidate/nxport.json
  receipt=$candidate/nxdeployment.json
  [[ -d $candidate ]] || return 0
  NXPORT_LAUNCHER_CANDIDATE=$candidate
  NXPORT_BOOTSTRAP_PATH=$bootstrap
  export NXPORT_BOOTSTRAP_PATH
  NXPORT_LAUNCHER_STAGE=validate-deployment
  if [[ -f $bootstrap && ! -L $bootstrap ]]; then
    :
  else
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: versioned nxbootstrap is missing or unsafe"
    return 0
  fi
  if [[ ! -f $manifest || -L $manifest ]]; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: nxport manifest is missing or unsafe"
    return 0
  fi
  if [[ ! -f $receipt || -L $receipt ]]; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: deployment receipt is missing or unsafe"
    return 0
  fi
  if ! nxport_deployment_receipt_matches "$receipt" 2>/dev/null; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: deployment receipt is stale or invalid"
    return 0
  fi
  NXPORT_LAUNCHER_STAGE=verify-manifest
  if ! nxport_file_sha256_matches "$manifest" "$NXPORT_MANIFEST_SHA256"; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: nxport manifest checksum mismatch"
    return 0
  fi
  NXPORT_LAUNCHER_STAGE=verify-bootstrap
  if ! nxport_file_sha256_matches "$bootstrap" "$NXPORT_BOOTSTRAP_SHA256"; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: versioned nxbootstrap checksum mismatch"
    return 0
  fi
  NXPORT_GAME_DIR=$(CDPATH= cd -- "$candidate" 2>/dev/null && pwd -P) ||
    return 0
  [[ $NXPORT_GAME_DIR != / ]] || return 0
  NXPORT_BOOTSTRAP_PATH=$NXPORT_GAME_DIR/$NXPORT_BOOTSTRAP_LIBRARY
  export NXPORT_BOOTSTRAP_PATH
  NXPORT_LAUNCHER_STAGE=source-bootstrap
  NXPORT_LAUNCHER_ERROR="$PORT_TITLE: versioned nxbootstrap failed to load"
  source "$NXPORT_GAME_DIR/$NXPORT_BOOTSTRAP_LIBRARY" || exit 1
  NXPORT_LAUNCHER_STAGE=validate-bootstrap-version
  if [[ ${NXBOOTSTRAP_VERSION:-} != "$NXPORT_BOOTSTRAP_VERSION" ]]; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: nxbootstrap version mismatch; expected $NXPORT_BOOTSTRAP_VERSION"
    exit 1
  fi
  if ! declare -F nxbootstrap_main >/dev/null 2>&1; then
    NXPORT_LAUNCHER_ERROR="$PORT_TITLE: nxbootstrap_main is unavailable"
    exit 1
  fi
  NXPORT_LAUNCHER_STAGE=nxbootstrap-main
  NXPORT_LAUNCHER_ERROR=
  nxbootstrap_main "$@"
  status=$?
  NXPORT_LAUNCHER_COMPLETED=1
  trap - EXIT
  exit "$status"
}

# Relative discovery covers PortMaster copies/symlinks without choosing a CFW.
cursor=$SCRIPT_DIR
depth=0
while [[ $depth -lt 5 ]]; do
  try_port "$cursor/$PORT_ID" "$@"
  try_port "$cursor/ports/$PORT_ID" "$@"
  try_port "$cursor/Ports/$PORT_ID" "$@"
  parent=$(dirname -- "$cursor")
  [[ $parent != "$cursor" ]] || break
  cursor=$parent
  depth=$((depth + 1))
done

for rom_root in \
  /roms /roms2 /storage/roms /userdata/roms \
  /mnt/mmc /mnt/mmc/roms /mnt/mmc/ROMS \
  /mnt/sdcard /mnt/sdcard/roms /mnt/sdcard/ROMS
do
  try_port "$rom_root/ports/$PORT_ID" "$@"
  try_port "$rom_root/Ports/$PORT_ID" "$@"
done

[[ -n $NXPORT_LAUNCHER_ERROR ]] ||
  NXPORT_LAUNCHER_ERROR="$PORT_TITLE: $PORT_ID runtime directory not found"
exit 1
