#!/bin/bash
# PORTMASTER: swordigo, Swordigo.sh
# Swordigo — generated by nxbootstrap 0.6.3.

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

NXBOOTSTRAP_FINISHED=0
NXBOOTSTRAP_ABORTING=0
nxbootstrap_finish() {
  [ "$NXBOOTSTRAP_FINISHED" = 0 ] || return 0
  NXBOOTSTRAP_FINISHED=1
  if command -v pm_finish >/dev/null 2>&1; then pm_finish || true; fi
}
nxbootstrap_abort_before_game() {
  local abort_status=$1
  [ "$NXBOOTSTRAP_ABORTING" = 0 ] || return 0
  NXBOOTSTRAP_ABORTING=1
  echo "== aborted before game start (status $abort_status) =="
  nxbootstrap_finish
  exit "$abort_status"
}
nxbootstrap_install_early_traps() {
  trap 'nxbootstrap_abort_before_game 130' INT
  trap 'nxbootstrap_abort_before_game 143' TERM
  trap 'nxbootstrap_abort_before_game 129' HUP
}
trap nxbootstrap_finish EXIT

# A signal before the game starts (mapper/extraction can take seconds) must
# still hand the screen back to the frontend instead of dying by default.
nxbootstrap_install_early_traps

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
elif [ -d "/storage/roms/ports/PortMaster/" ]; then
  controlfolder="/storage/roms/ports/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

# Sourced firmware files must be regular (a symlinked control.txt/mod can
# point anywhere), and CFW_NAME reaches a source path so it must never carry
# a separator or shell-hostile byte.
if [ -f "$controlfolder/control.txt" ] && [ ! -L "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  trap nxbootstrap_finish EXIT
  nxbootstrap_install_early_traps
  case "${CFW_NAME-}" in
    *[!A-Za-z0-9._-]*|'') NXBOOTSTRAP_MOD_NAME='' ;;
    *) NXBOOTSTRAP_MOD_NAME=$CFW_NAME ;;
  esac
  if [ -n "$NXBOOTSTRAP_MOD_NAME" ] && \
     [ -f "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ] && \
     [ ! -L "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ]; then
    source "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt"
    trap nxbootstrap_finish EXIT
    nxbootstrap_install_early_traps
  fi
  command -v get_controls >/dev/null 2>&1 && get_controls
  trap nxbootstrap_finish EXIT
  nxbootstrap_install_early_traps
fi

GAMEDIR="/$directory/ports/swordigo"
[ -d "$GAMEDIR" ] || GAMEDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)/swordigo"
# Physical path: ROM roots are often symlinks (/roms -> /storage/roms) and
# tools that compare canonical containment would reject the logical path.
cd "$GAMEDIR" || exit 1
GAMEDIR=$(pwd -P)

[ -s "$GAMEDIR/log.txt" ] && mv -f "$GAMEDIR/log.txt" "$GAMEDIR/log.prev.txt" 2>/dev/null
exec > "$GAMEDIR/log.txt" 2>&1
echo "== Swordigo | nxbootstrap 0.6.3 | cfw=${CFW_NAME:-none} =="

# The executable is itself required and is touched before the owner-data phase.
NXBOOTSTRAP_EXECUTABLE=$(readlink -f "$GAMEDIR/swordigo-nextos" 2>/dev/null) || NXBOOTSTRAP_EXECUTABLE=""
case "$NXBOOTSTRAP_EXECUTABLE" in
  "$GAMEDIR"/*) ;;
  *) NXBOOTSTRAP_EXECUTABLE="" ;;
esac
if [ -z "$NXBOOTSTRAP_EXECUTABLE" ] || [ ! -f "$NXBOOTSTRAP_EXECUTABLE" ] || \
   [ ! -s "$NXBOOTSTRAP_EXECUTABLE" ] || [ -L "$GAMEDIR/swordigo-nextos" ]; then
  echo "ERROR: executable is missing or unsafe: swordigo-nextos"
  nxbootstrap_finish
  exit 1
fi

# Exec bits do not survive zip/FAT/Windows extraction.
$ESUDO chmod +x "$NXBOOTSTRAP_EXECUTABLE" "$GAMEDIR/nxextract-ui" \
  "$GAMEDIR"/*.sh 2>/dev/null || true
$ESUDO chmod 666 "$CUR_TTY" /dev/uinput 2>/dev/null || true

# Keep the text console dark across the KMSDRM transition: a slow-loading
# engine (Unity/IL2CPP) would otherwise leave the tty visible -- PortMaster
# get_controls output and boot text -- until its GL window covers the screen,
# and the frontend hand-off already resets it (\033c) on exit. Hide the cursor
# and clear the screen; harmless on fbdev where nothing overlaps.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && \
  printf '\033[?25l\033[2J\033[H' > "$CUR_TTY" 2>/dev/null || true

# One stable lock per port ID, outside the ROM. Replacing the ELF cannot create
# a new lock inode and allow a second game to fight for fb0/audio/input.
NXBOOTSTRAP_LOCK_ROOT=${XDG_RUNTIME_DIR:-}
if [ "${NXBOOTSTRAP_LOCK_ROOT#/}" = "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  NXBOOTSTRAP_LOCK_ROOT=/tmp
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_ROOT=$(cd "$NXBOOTSTRAP_LOCK_ROOT" 2>/dev/null && pwd -P) || {
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
}
case "$NXBOOTSTRAP_LOCK_ROOT" in
  "$GAMEDIR"|"$GAMEDIR"/*)
    echo "ERROR: instance lock directory must be outside the game"
    nxbootstrap_finish
    exit 1
    ;;
esac
NXBOOTSTRAP_LOCK_DIR="$NXBOOTSTRAP_LOCK_ROOT/.nxbootstrap-${UID:-$(id -u)}"
if [ ! -e "$NXBOOTSTRAP_LOCK_DIR" ] && [ ! -L "$NXBOOTSTRAP_LOCK_DIR" ]; then
  (umask 077; mkdir "$NXBOOTSTRAP_LOCK_DIR") 2>/dev/null || true
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_DIR" ] || [ -L "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_DIR" ] || [ ! -w "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_DIR" ] || \
   ! chmod 0700 "$NXBOOTSTRAP_LOCK_DIR" 2>/dev/null; then
  echo "ERROR: unsafe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_FILE="$NXBOOTSTRAP_LOCK_DIR/nxport-swordigo.flock"
if [ -e "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ]; then
  if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
     [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ]; then
    echo "ERROR: unsafe instance lock file"
    nxbootstrap_finish
    exit 1
  fi
fi
NXBOOTSTRAP_OLD_UMASK=$(umask)
umask 077
{ exec 9>&-; } 2>/dev/null || true
if ! { exec 9>>"$NXBOOTSTRAP_LOCK_FILE"; } 2>/dev/null; then
  umask "$NXBOOTSTRAP_OLD_UMASK"
  echo "ERROR: cannot open the instance lock"
  nxbootstrap_finish
  exit 1
fi
umask "$NXBOOTSTRAP_OLD_UMASK"
# POSIX/BusyBox/Toybox ls supplies nlink; Bash -ef proves the opened inode.
# Never depend on external stat: some supported muOS images omit it.
NXBOOTSTRAP_LOCK_META=()
IFS=' ' read -r -a NXBOOTSTRAP_LOCK_META \
  <<< "$(LC_ALL=C command ls -Lldn /proc/self/fd/9 2>/dev/null)"
NXBOOTSTRAP_LOCK_LINKS=${NXBOOTSTRAP_LOCK_META[1]:-}
if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ] || [ "$NXBOOTSTRAP_LOCK_LINKS" != 1 ] || \
   ! [ "$NXBOOTSTRAP_LOCK_FILE" -ef /proc/self/fd/9 ]; then
  { exec 9>&-; } 2>/dev/null || true
  echo "ERROR: instance lock identity is unsafe"
  nxbootstrap_finish
  exit 1
fi
unset NXBOOTSTRAP_LOCK_META NXBOOTSTRAP_LOCK_LINKS
if ! flock -n 9; then
  echo "another instance holds the lock; not double-launching"
  nxbootstrap_finish
  exit 1
fi

# NXExtract owner-data phase (BYO data): runs before the game, other process.
NXDIR=""
[ -f "$GAMEDIR/nxextract/run-extractor.sh" ] && NXDIR="$GAMEDIR/nxextract"
[ -z "$NXDIR" ] && [ -f "$GAMEDIR/run-extractor.sh" ] && NXDIR="$GAMEDIR"
NXEXTRACT_REQUESTED=1
if [ "$NXEXTRACT_REQUESTED" = 1 ]; then
  NXEXTRACT_INCOMPLETE=0
  [ -n "$NXDIR" ] && [ ! -L "$NXDIR" ] || NXEXTRACT_INCOMPLETE=1
  for nxfile in "$GAMEDIR/extractor.json" "$NXDIR/run-extractor.sh" \
    "$NXDIR/nxextract.py" "$NXDIR/nxextract-runtime-env.sh"; do
    [ -f "$nxfile" ] && [ -s "$nxfile" ] && [ ! -L "$nxfile" ] || NXEXTRACT_INCOMPLETE=1
  done
  if [ "$NXEXTRACT_INCOMPLETE" = 1 ]; then
    echo "ERROR: incomplete NXExtract integration"
    nxbootstrap_finish
    exit 1
  fi
  $ESUDO chmod +x "$NXDIR/nxextract-ui" 2>/dev/null || true
  NXEXTRACT_GAME_DIR="$GAMEDIR" \
    bash "$NXDIR/nxextract-runtime-env.sh" \
    bash "$NXDIR/run-extractor.sh" || {
      echo "ERROR: game data installation did not complete"
      nxbootstrap_finish
      exit 1
    }
fi
unset NXDIR NXEXTRACT_REQUESTED NXEXTRACT_INCOMPLETE nxfile

# Manifest-owned payload gate: extraction/prepare must finish before launch.
NXBOOTSTRAP_REQUIRED_FILES='swordigo-nextos
libswordigo.so
res/7c.mp3
alsoft.conf'
while IFS= read -r required_file; do
  [ -n "$required_file" ] || continue
  required_path=$(readlink -f "$GAMEDIR/$required_file" 2>/dev/null) || required_path=""
  case "$required_path" in
    "$GAMEDIR"/*) ;;
    *) required_path="" ;;
  esac
  if [ -z "$required_path" ] || [ ! -f "$required_path" ] || \
     [ ! -s "$required_path" ] || [ -L "$GAMEDIR/$required_file" ]; then
    echo "ERROR: required file is missing or unsafe: $required_file"
    nxbootstrap_finish
    exit 1
  fi
done <<< "$NXBOOTSTRAP_REQUIRED_FILES"
unset NXBOOTSTRAP_REQUIRED_FILES required_file required_path
# Saves and configuration stay inside the port directory.
export HOME="$GAMEDIR"
# An empty CFW mapping must not clobber a valid inherited one (contract:
# honor the existing mapping and only log when the CFW publishes nothing).
[ -n "$sdl_controllerconfig" ] && export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Optional per-port adapter: may export env or replace $BIN / $BIN_PRELOAD.
BIN="$GAMEDIR/swordigo-nextos"
[ -f "$GAMEDIR/port-env.sh" ] && [ ! -L "$GAMEDIR/port-env.sh" ] && . "$GAMEDIR/port-env.sh"

command -v pm_platform_helper >/dev/null 2>&1 && pm_platform_helper "$BIN"

# Host phase ends here: game/private library paths must never contaminate
# pm_platform_helper or the setup tools above, so they enter only now.
# Firmware/PortMaster overlays first; preserve distro-local providers before
# the system defaults, then append the game's own directory.
LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.aarch64" \
         /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
         /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
         /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && LIBS="${LIBS:+$LIBS:}$d"
done
export LD_LIBRARY_PATH="${LIBS}:$GAMEDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
trap nxbootstrap_finish EXIT
nxbootstrap_install_early_traps

# Manifest-owned runtime contract: reassert after every mutable shell hook.
export NXCOMPAT_PORT_ID=swordigo
export NXCOMPAT_GAME_DIR="$GAMEDIR"
export NXCOMPAT_REQUIRED_CAPABILITIES='host.portmaster
graphics.window
graphics.egl
graphics.drawable
audio.output-open
input.controller-mapping
input.controller-api'
export NXCOMPAT_ENABLED_QUIRKS='adapter.gl-provider-reexec-preload
adapter.gl-provider-probe-init-reexec
game.swordigo.present-alpha-one
game.swordigo.fullscreen-desktop
game.swordigo.present-finish'
export NXCOMPAT_RUNTIME_REPORT=log-and-logo

game_pid=
NXBOOTSTRAP_CHILD_STARTTIME=
NXBOOTSTRAP_SHUTDOWN_REQUESTED=0
NXBOOTSTRAP_TERM_SENT=0
NXBOOTSTRAP_SIGNAL_COUNT=0
nxbootstrap_capture_child_starttime() {
  local child_stat child_rest
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  NXBOOTSTRAP_CHILD_STARTTIME=${20}
}
nxbootstrap_child_alive() {
  local child_stat child_rest child_state child_start
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || return 1
  builtin kill -0 "$game_pid" 2>/dev/null || return 1
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  child_state=$1
  child_start=${20}
  case "$child_state" in Z|X) return 1 ;; esac
  [ "$child_start" = "$NXBOOTSTRAP_CHILD_STARTTIME" ]
}
nxbootstrap_signal_child() {
  [ "$NXBOOTSTRAP_TERM_SENT" = 0 ] || return 0
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || \
    nxbootstrap_capture_child_starttime || return 0
  nxbootstrap_child_alive || return 0
  NXBOOTSTRAP_TERM_SENT=1
  builtin kill -TERM "$game_pid" 2>/dev/null || true
}
nxbootstrap_request_shutdown() {
  NXBOOTSTRAP_SIGNAL_COUNT=$((NXBOOTSTRAP_SIGNAL_COUNT + 1))
  if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ]; then
    NXBOOTSTRAP_SHUTDOWN_REQUESTED=1
  fi
  nxbootstrap_signal_child || true
}
trap nxbootstrap_request_shutdown INT TERM HUP
# Close the lock fd IN THE CHILD ONLY (9>&-): the launcher keeps fd 9 and the
# flock for the whole game, but the game — and any detached helper it forks —
# must not inherit the lock, or an orphaned grandchild would hold the port lock
# after the launcher exits and block the next launch.
if [ -n "$BIN_PRELOAD" ]; then
  LD_PRELOAD="$BIN_PRELOAD${LD_PRELOAD:+:$LD_PRELOAD}" "$BIN" "$GAMEDIR" "$@" 9>&- &
else
  "$BIN" "$GAMEDIR" "$@" 9>&- &
fi
game_pid=$!
nxbootstrap_capture_child_starttime || NXBOOTSTRAP_CHILD_STARTTIME=""
[ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ] || nxbootstrap_signal_child
if wait "$game_pid"; then status=0; else status=$?; fi
if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 1 ]; then
  trap '' INT TERM HUP
  NXBOOTSTRAP_SHUTDOWN_TICKS=10
  while [ "$NXBOOTSTRAP_SHUTDOWN_TICKS" -gt 0 ] && nxbootstrap_child_alive; do
    sleep 1 || true
    NXBOOTSTRAP_SHUTDOWN_TICKS=$((NXBOOTSTRAP_SHUTDOWN_TICKS - 1))
  done
  if nxbootstrap_child_alive; then
    echo "== termination deadline expired; sending KILL =="
    builtin kill -KILL "$game_pid" 2>/dev/null || true
  fi
  # Each handled frontend signal can contribute one synthetic 128+n result.
  NXBOOTSTRAP_REWAIT_BUDGET=$NXBOOTSTRAP_SIGNAL_COUNT
  while [ "$NXBOOTSTRAP_REWAIT_BUDGET" -gt 0 ]; do
    case "$status" in 129|130|143) ;; *) break ;; esac
    NXBOOTSTRAP_REWAIT_BUDGET=$((NXBOOTSTRAP_REWAIT_BUDGET - 1))
    if wait "$game_pid" 2>/dev/null; then status=0; else status=$?; fi
  done
else
  # 128+n can also be wait itself being interrupted; recover the child truth.
  while [ "$status" -gt 128 ] && nxbootstrap_child_alive; do
    if wait "$game_pid"; then status=0; else status=$?; fi
  done
fi
echo "== end (status $status) =="

# The game may leave the console keymap off (K_OFF); reset before handing back.
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && printf '\033c' > "$CUR_TTY" 2>/dev/null
nxbootstrap_finish
exit $status
